
## == internvideo backbone == ## 
model:
  arch: patch_and_fuse_internvideo
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "pretrained_ckpt/InternVideo/models/InternVideo-MM-L-14.ckpt"
  pretrained: "<path to trained KP-Perceiver-VTC on SSv2>/checkpoint_best.pth" #TODO: set trained Knowledge Patcher checkpoint path
   
  text_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # text_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  vision_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 1024 # vision_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  objectives: ["video_text_contrastive"]
  loss_weighting: [1.0]
  if_use_attn_guidance: False
  if_use_dual_perceiver: False
  if_add_temporal_emebdding: True
  num_frms: 8
  temp_emb_drop_out: 0.1
  if_as_knowledge_fuser: True
  knowledge_fuser_type: "xattn"
  train_knowledge_fuser_jointly: True


datasets:
  acdybench_ssv2_224x224_5fps:
    type: "action_antonyms_and_object_shuffled"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "minimum_text"
      eval:
        name: "minimum_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "action_antonym"
    neg_sampling_same_clip: 0
    # eval_only: True
    
    # other arguements
    train_k: null # sample a subset of k instances
    eval_k: null # sample a subset of k instances, reduce evaluation time
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_patch_and_fuse
  
  # task object name
  task: acdybench

  # which module is used for inference ["backbone", "knowledge_patcher", "knowledge_patcher_baseline"]
  eval_module: knowledge_patcher
  eval_task: action_antonym

  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 1 # Train knowledge fuser for another epoch on SSv2 label (same as the KP-Perceiver-VTC training)

  batch_size_train: 32
  batch_size_eval: 4
  
  num_workers: 4

  seed: 42
  output_dir: "output/downstream_tasks/ssv2_label/train/patch_and_fuse__internvideo"

  amp: False
  resume_ckpt_path: null

  evaluate: False
  
  train_splits: ["train"]
  valid_splits: ["val"]
  # test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
