# modified from https://github.com/salesforce/LAVIS/tree/main/lavis/configs

model:
  arch: patch_and_fuse_internvideo
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "pretrained_ckpt/InternVideo/InternVideo-MM-L-14.ckpt"


datasets:
  acdybench_ssv2_224x224_5fps:
    type: "action_antonyms_and_object_shuffled"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "minimum_text"
      eval:
        name: "minimum_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "action_antonym" # ["video_text_matching", "action_antonym", "object_shuffle", "reversed_video"]
    neg_sampling_same_clip: 0
    eval_only: True
    
    # other arguements
    train_k: null # sample a subset of k instances
    eval_k: null # sample a subset of k instances, reduce evaluation time
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_patch_and_fuse
  
  # task object name
  task: acdybench

  # which module is used for inference ["backbone", "knowledge_patcher"]
  eval_module: backbone
  eval_task: action_antonym

  batch_size_train: 32
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "output/acdybench/eval/InternVideo/ssv2__InternVideo_backbone__action_antonym"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  valid_splits: ["val"]
  # test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
