 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: physical_knowledge_patcher_internvideo # w/o jointly train vis encoder using action prediction
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/third_party/InternVideo/models/InternVideo-MM-L-14.ckpt"
  pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/physical_knowledge_bench/train/SSv2__knowledge_patcher_internvideo_inverse_dynamic_only/20230306231/checkpoint_best.pth"

  query_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # text_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  knowledge_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 1024 # vision_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  dynamic_model_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # latent query dim
    dim_head: 64
    heads: 8
    ff_mult: 2

  objectives: ["inverse_dynamic"]
  loss_weighting: [1.0]

datasets:
  downstream_tasks_retrieval_temporal:
    type: "default"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "minimum_text"
      eval:
        name: "minimum_text"
    
    # IMPORTANT configs:
    fps: 5
    task: v1.0_2.4k
    subset: ssv2
    neg_sampling_same_clip: 0
    eval_only: True
    
    # other arguements
    train_k: null # sample a subset of k instances
    eval_k: null # sample a subset of 3000 instances, reduce evaluation time
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_vl_dynamic_modeling
  
  # task object name
  task: downstream_tasks_retrieval

  # which module is used for inference ["backbone", "knowledge_patcher"]
  eval_module: knowledge_patcher
  eval_task: v1.0_2.4k

  batch_size_train: 32
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/downstream_tasks/eval/Temporal/Temporal_ssv2_2.4k__from_ssv2_internvideo_inverse_dm_only"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  valid_splits: ["val"]
  # test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
