# modified from https://github.com/salesforce/LAVIS/tree/main/lavis/configs


model:
  arch: patch_and_fuse_internvideo
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "pretrained_ckpt/InternVideo/InternVideo-MM-L-14.ckpt"



datasets:
  actionbench_ego4d_224x224_5fps: # using subset of egoclip for training and egomcq for validation
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "vl_dynamic_ego4d_text"
      eval:
        name: "vl_dynamic_ego4d_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "reversed_video" # evaluation task: ["video_text_matching", "action_antonym", "reversed_video"]
    neg_sampling_same_clip: 0 # evaluation set to 0
    eval_only: True
    
    # other arguements
    k: null # sample a subset of k instances
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_patch_and_fuse
  
  # task object name
  task: actionbench

  # which module is used for inference ["backbone", "knowledge_patcher"]
  eval_module: backbone
  eval_task: reversed_video

  batch_size_train: 32
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "output/actionbench/eval/InternVideo/ego4d__InternVideo_backbone__reversed_video"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  # valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
