 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: physical_knowledge_patcher_internvideo_reformulated
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/third_party/InternVideo/models/InternVideo-MM-L-14.ckpt"
  pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/physical_knowledge_bench_filtered_on_FDM/train/ego4d/ego4d__knowledge_patcher_internvideo_reformulated_v4_single_new_temporal_emb_w_dropout_less_max_weight_more_FDM_further/20230402220/checkpoint_best.pth"

  text_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # text_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  vision_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 1024 # vision_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  objectives: ["video_text_contrastive","inverse_dynamic","forward_dynamic"]
  loss_weighting: [1.0,1.0,0.3]
  if_use_attn_guidance: False
  if_use_dual_perceiver: False
  if_add_temporal_emebdding: True
  num_frms: 8
  temp_emb_drop_out: 0.0
  state_change_filtering_for_FDM: True

datasets:
  physical_knowledge_bench_ego4d_224x224_5fps: # using subset of egoclip for training and egomcq for validation
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "vl_dynamic_ego4d_text"
      eval:
        name: "vl_dynamic_ego4d_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "action_antonym" # evaluation task: ["video_text_matching", "action_antonym", "consequence_precondition", "reversed_video"]
    neg_sampling_same_clip: 0 # evaluation set to 0
    eval_only: True
    
    # other arguements
    k: null # sample a subset of k instances
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

    # filtering for reversed video
    # state_change_filtering: True

run:
  # use custom runner
  runner: runner_base_vl_dynamic_modeling
  
  # task object name
  task: physical_knowledge_bench

  # which module is used for inference ["backbone", "knowledge_patcher", "knowledge_patcher_baseline"]
  # eval_module: backbone
  eval_module: knowledge_patcher
  eval_task: action_antonym

  batch_size_train: 16
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/physical_knowledge_bench_filtered/eval/ego4d/ego4d__internvideo_reformuated_v4_single_new_temp_emb_dropout_less_max_1epoch_more_weight_FDM_further__action_antonym"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  # valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
