datasets:
  downstream_tasks_retrieval_ssv2_224x224_5fps: # name of the dataset builder
    dataset_card: dataset_cards/downstream_task_ssv2.md
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          path: datasets/SSv2/ssv2_label_ssv2_template
        val:
          path: datasets/SSv2/ssv2_label_ssv2_template
      videos:
        path: datasets/SSv2/video_clips/clips_downsampled_5fps_downsized_224x224