 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: physical_knowledge_patcher_internvideo # w/o jointly train vis encoder using action prediction
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/third_party/InternVideo/models/InternVideo-MM-L-14.ckpt"
  pretrained: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/physical_knowledge_bench/train/SSv2__knowledge_patcher_internvideo_inverse_dynamic_only/20230306231/checkpoint_best.pth"

  query_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # text_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  knowledge_perceiver_config:
    dim: 768 # latent query dim
    k_v_dim: 1024 # vision_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  dynamic_model_config:
    dim: 768 # latent query dim
    k_v_dim: 768 # latent query dim
    dim_head: 64
    heads: 8
    ff_mult: 2

  objectives: ["inverse_dynamic"]
  loss_weighting: [1.0]

datasets:
  physical_knowledge_bench_ego4d_224x224_5fps: # using subset of egoclip for training and egomcq for validation
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "vl_dynamic_ego4d_text"
      eval:
        name: "vl_dynamic_ego4d_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "reversed_video" # evaluation task: ["video_text_matching", "action_antonym", "consequence_precondition", "reversed_video"]
    neg_sampling_same_clip: 0 # evaluation set to 0
    
    eval_only: True
    
    # other arguements
    k: null # sample a subset of k instances
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_vl_dynamic_modeling
  
  # task object name
  task: physical_knowledge_bench

  # which module is used for inference ["backbone", "knowledge_patcher", "knowledge_patcher_baseline"]
  # eval_module: backbone
  eval_module: knowledge_patcher
  eval_task: reversed_video

  batch_size_train: 16
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/physical_knowledge_bench/eval/cross_domain/cross_domain_ssv2-ego4d__internvideo_v1_1epoch_inverse_dm_only__reversed_video"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  # valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
