 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_vl_dynamicmodel_pretrain # w/o jointly train vis encoder using action prediction

  model_type: base
  load_pretrained: True

  queue_size: 57600
  alpha: 0.2 # origianl 0.4

datasets:
  ego4d_dynamic_modeling_egovlp_v1: # using subset of egoclip for training and egomcq for validation
    vis_processor:
        train:
          name: "vl_dynamic_blip_ego4d_image_train" # disable RandomHorizontalFlip; lowering aug level to preserve more fine-grained feature
          image_size: 224
          min_scale: 0.9
          max_scale: 1.0
        eval:
          name: "vl_dynamic_blip_ego4d_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "vl_dynamic_ego4d_text"
        eval:
          name: "vl_dynamic_ego4d_text"
    # sample a subset of k instances
    k: null
    # other arguements
    frm_sampling_strategy: "firstlast" # take the first and last frame as start and end state
    num_frm: 2
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

    fps: 30 # IMPORTANT: if downsampled, use 5 fps

    train_cached_root: null
    val_cached_root: null

run:
  # use custom runner (default is runner_base)
  runner: runner_base_vl_dynamic_modeling
  # task
  task: ego4d_dynamic_modeling_egovlp_v1
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 5
  # batch_size_train: 32
  # batch_size_eval: 64
  batch_size_train: 64
  batch_size_eval: 64
  
  num_workers: 8

  max_len: 30
  min_len: 5
  num_beams: 3

  seed: 42
  output_dir: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/ego4d_dynamic_modeling_egovlp_v1/pretrain_model_v1"

  amp: False
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: ["val"]
  # test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
