# modified from https://github.com/salesforce/LAVIS/tree/main/lavis/configs

model:
  arch: patch_and_fuse_singularity
  model_type: singularity_temporal_17m
  load_pretrained: True
  backbone_config_yaml: "Singularity/configs/pretrained_singularity_temporal_17m.yaml"

  text_perceiver_config:
    dim: 256 # latent query dim
    k_v_dim: 768 # text_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  vision_perceiver_config:
    dim: 256 # latent query dim
    k_v_dim: 768 # vision_width
    depth: 1
    dim_head: 64
    heads: 8
    num_latents: 16
    ff_mult: 2

  objectives: ["video_text_contrastive"]
  loss_weighting: [1.0]
  if_use_attn_guidance: False
  if_use_dual_perceiver: False
  if_add_temporal_emebdding: False
  num_frms: 8
  temp_emb_drop_out: 0.0
  # if_as_knowledge_fuser: True
  # knowledge_fuser_type: "xattn"
  # train_knowledge_fuser_jointly: True

datasets:
  acdybench_ego4d_224x224_5fps: # using subset of egoclip for training and egomcq for validation
    type: "object_shuffled"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "vl_dynamic_ego4d_text"
      eval:
        name: "vl_dynamic_ego4d_text"
    
    # IMPORTANT configs: 
    fps: 5 # if downsampled, use 5 fps
    task: "object_shuffle" # evaluation task: ["video_text_matching", "action_antonym", "reversed_video"]
    neg_sampling_same_clip: 0 # evaluation set to 0
    eval_only: True
    
    # other arguements
    k: null # sample a subset of k instances
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_patch_and_fuse
  
  # task object name
  task: acdybench

  # which module is used for inference ["backbone", "knowledge_patcher"]
  eval_module: backbone
  eval_task: object_shuffle

  batch_size_train: 32
  batch_size_eval: 4
  num_workers: 4

  seed: 42
  output_dir: "output/acdybench/eval/Singularity/ego4d__Singularity_backbone__object_shuffle"

  amp: False
  resume_ckpt_path: null

  evaluate: True 
  # train_splits: ["train"]
  # valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
