model:
  arch: patch_and_fuse_internvideo_mcqa
  model_type: InternVideo-MM-L-14
  load_pretrained: True
  backbone_pretrained: "pretrained_ckpt/InternVideo/InternVideo-MM-L-14.ckpt"

datasets:
  downstream_tasks_qa_nextqa_224x224_5fps:
    type: "default"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "minimum_text"
      eval:
        name: "minimum_text"
    
    # IMPORTANT configs:
    task: 5way-multiple-choice-qa # 
    neg_sampling_same_clip: 0
    eval_only: True
    
    # other arguements
    train_k: null # sample a subset of k instances
    eval_k: null # sample a subset of k instances, reduce evaluation time
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_patch_and_fuse
  
  # task object name
  task: downstream_tasks_multi_choice_qa

  # which module is used for inference ["backbone", "knowledge_patcher"]
  eval_module: backbone
  eval_task: 5way-multiple-choice-qa

  batch_size_train: 32
  batch_size_eval: 8
  num_workers: 4

  seed: 42
  output_dir: "output/downstream_tasks/NextQA/eval/backbone_zero-shot"

  amp: False
  resume_ckpt_path: null

  evaluate: True
  
  # train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
