 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: physical_knowledge_patcher_singularity_baseline_simple_mcqa # w/o jointly train vis encoder using action prediction
  model_type: singularity_temporal_17m
  load_pretrained: True
  backbone_config_yaml: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/Singularity/configs/pretrained_singularity_temporal_17m.yaml"
  pretrained: /shared/nas/data/m1/wangz3/phy-lm-vid/src/output/NextQA/train/singularity/nextqa_singularity_baseline_simple_5epoch/20230406024/checkpoint_best.pth

datasets:
  downstream_tasks_qa_nextqa_224x224_5fps:
    type: "default"
    vis_processor:
      train:
        name: "video_train"
        image_size: 224
      eval:
        name: "internvideo_eval"
        image_size: 224
    text_processor:
      train:
        name: "minimum_text"
      eval:
        name: "minimum_text"
    
    # IMPORTANT configs:
    task: 5way-multiple-choice-qa
    neg_sampling_same_clip: 0
    eval_only: False
    
    # other arguements
    train_k: null # sample a subset of k instances
    eval_k: null # sample a subset of 3000 instances, reduce evaluation time
    frm_sampling_strategy: "uniform" # take the first and last frame as start and end state
    num_frm: 8
    train_frame_height: 224
    train_frame_width: 224
    eval_frame_height: 224
    eval_frame_width: 224

run:
  # use custom runner
  runner: runner_base_vl_dynamic_modeling
  
  # task object name
  task: physical_knowledge_bench

  # which module is used for inference ["backbone", "knowledge_patcher"]
  # eval_module: backbone
  eval_module: knowledge_patcher_baseline
  eval_task: video_text_matching

  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 5

  batch_size_train: 8
  batch_size_eval: 4
  
  num_workers: 4

  seed: 42
  output_dir: "/shared/nas/data/m1/wangz3/phy-lm-vid/src/output/NextQA/train/singularity/nextqa_singularity_baseline_simple_10epoch"

  amp: False
  resume_ckpt_path: null

  evaluate: False
  
  train_splits: ["train"]
  valid_splits: ["val"]
  # test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
